### ISSUE TITLE
ID107HR incorrect PIN_VIBRATE mapping?

### ISSUE THREAD

**Issue by micooke** [rogerclarkmelbourne/arduino-nRF5-customised#2]
Im not sure if i have a non-standard board, but the vibrator is located on pin 6, not pin 8 on my board.
Is this a copy/paste error from the D003 or is my board 'special'

Early stages of my investigation but SPI pins are correct and I2C are not. I need to investigate a bit more though.

**Comment by micooke** [comment]
@goran-mahovlic - can you confirm that the following is correct:
#define PIN_VIBRATE 6
#define SCL 24
#define SDA 23

Also, what is the function of pin 22? That is also on the ribbon to the Si1142.
Cheers

**Comment by goran-mahovlic** [comment]
Latest pinout that I have for ID107HR is:
    KX022 accelerometer (I2C, SDA pin 14, SCL pin 16)
    64x32 SPI OLED display (RESET pin 30, CS pin 29, DC pin 0)
    STM1132 heart rate sensor (software I2C, SDA pin 26, SCL pin 28)
    Vibration motor (pin 8)
    Soft (capacitive) button (pin 7)
    Hardware button (pin 4)

**Comment by micooke** [comment]
Thanks Goran! I was browsing through your nrf51822 [gitter](https://gitter.im/nRF51822-Arduino-Mbed-smart-watch/Lobby) and was hoping you had the same pinout as me, but it looks like mine is different.

Toggling gpio 22,23,24 sets the ribbon pin 4,3,2 LOW (pin range 0-6). So its definitely a combination of 22,23,24 that is attached to my HRM sensor. I2C scanning pin with sda, scl = 16,17 produces nothing for me so it looks like its back to the microscope for me!

For reference, @sanpii has the same board as mine [ID107 ver2.4](https://github.com/sanpii/open-id107/blob/master/hardware/photo/IMG_4246.png)

**Comment by micooke** [comment]
Hi Goran, sorry last question. What software i2c library did you use? None of the ones ive tested work with the nrf chips

**Comment by micooke** [comment]
Yes sorry, i meant for the heartrate sensor.
